import { createContext, useContext, useState } from 'react'

export const LANGUAGES = [
  { code: 'en', label: 'EN', name: 'English' },
  { code: 'es', label: 'ES', name: 'Español' },
  { code: 'pl', label: 'PL', name: 'Polski' },
  { code: 'fil', label: 'FIL', name: 'Filipino' },
]

const UI = {
  en: {
    appSubtitle:           'Koine for Everyone',
    chapterLocked:         'Chapter Locked',
    chapterLockedMsg:      'This chapter is not yet available. Complete Unit 1 to unlock future units.',
    loading:               'Loading chapter…',
    // Tab labels
    tabStory:              'Story',
    tabVocabulary:         'Vocabulary',
    tabGrammar:            'Grammar',
    tabExercises:          'Exercises',
    tabVisual:             'Visual Story',
    tabConversations:      'Questions',
    // Vocabulary tab
    vocabFlashcards:       'Vocabulary Flashcards',
    reviews:               'reviews',
    tapToReveal:           'Tap to reveal',
    tapToFlipBack:         'Tap to flip back',
    prev:                  '← Previous',
    next:                  'Next →',
    reveal:                'Reveal',
    hide:                  'Hide',
    allWords:              'All Words',
    words:                 'words',
    seen:                  'Seen',
    // Story tab
    clickInstruction:      'Click a word to see its meaning. Double-click to see its picture.',
    showTranslation:       'Show Translation',
    hideTranslation:       'Hide Translation',
    // Exercises tab
    submit:                'Submit',
    tryAgain:              'Try Again',
    answered:              'answered',
    secMultipleChoice:     'Multiple Choice',
    secTrueOrFalse:        'True or False',
    secYesOrNo:            'Yes or No',
    secCorrectOrNot:       'Correct or Not',
    secFillBlank:          'Fill in the Blank',
    secChangePerson:       'Change the Person',
    secInfinitives:        'Infinitives',
    secImperatives:        'Imperatives',
    secContractVerbs:      'Contract Verbs',
    secFillCase:           'Fill the Case',
    secPrepositions:       'Prepositions',
    secConversations:      'Questions',
    // Visual story
    storyOverview:         'Story Overview',
    illustrationSoon:      'Illustration coming soon',
    // Sidebar / Vocab index
    tableOfContents:       'Table of Contents',
    allVocabulary:         'All Vocabulary',
    vocabSubtitle:         'All vocabulary · Units 1 & 2',
    searchPlaceholder:     'Search Greek or English…',
    clearFilters:          'Clear filters',
    byLesson:              'By Lesson',
    alphabetical:          'Α–Ω Alphabetical',
    colGreek:              'Greek',
    colEnglish:            'English',
    colType:               'Type',
    colLesson:             'Lesson',
    noWordsMatch:          'No words match your filters.',
    // POS categories
    catNoun:               'Noun',
    catVerb:               'Verb',
    catAdjective:          'Adjective',
    catAdverb:             'Adverb',
    catPreposition:        'Preposition',
    catConjunction:        'Conjunction',
    catPronoun:            'Pronoun',
    catParticle:           'Particle',
    catOther:              'Other',
  },
  es: {
    appSubtitle:           'Lector de Griego Koiné',
    chapterLocked:         'Capítulo bloqueado',
    chapterLockedMsg:      'Este capítulo aún no está disponible. Completa la Unidad 1 para desbloquear futuras unidades.',
    loading:               'Cargando capítulo…',
    tabStory:              'Historia',
    tabVocabulary:         'Vocabulario',
    tabGrammar:            'Gramática',
    tabExercises:          'Ejercicios',
    tabVisual:             'Historia visual',
    tabConversations:      'Preguntas',
    vocabFlashcards:       'Tarjetas de vocabulario',
    reviews:               'repasos',
    tapToReveal:           'Toca para revelar',
    tapToFlipBack:         'Toca para voltear',
    prev:                  '← Anterior',
    next:                  'Siguiente →',
    reveal:                'Revelar',
    hide:                  'Ocultar',
    allWords:              'Todas las palabras',
    words:                 'palabras',
    seen:                  'Visto',
    clickInstruction:      'Toca una palabra para ver su significado. Toca dos veces para ver su imagen.',
    showTranslation:       'Mostrar traducción',
    hideTranslation:       'Ocultar traducción',
    submit:                'Enviar',
    tryAgain:              'Intentar de nuevo',
    answered:              'respondidas',
    secMultipleChoice:     'Opción múltiple',
    secTrueOrFalse:        'Verdadero o Falso',
    secYesOrNo:            'Sí o No',
    secCorrectOrNot:       'Correcto o No',
    secFillBlank:          'Completar el espacio',
    secChangePerson:       'Cambiar la persona',
    secInfinitives:        'Infinitivos',
    secImperatives:        'Imperativos',
    secContractVerbs:      'Verbos contractos',
    secFillCase:           'Completar el caso',
    secPrepositions:       'Preposiciones',
    secConversations:      'Preguntas',
    storyOverview:         'Resumen de la historia',
    illustrationSoon:      'Ilustración próximamente',
    tableOfContents:       'Tabla de contenido',
    allVocabulary:         'Todo el vocabulario',
    vocabSubtitle:         'Todo el vocabulario · Unidades 1 y 2',
    searchPlaceholder:     'Buscar en griego o español…',
    clearFilters:          'Borrar filtros',
    byLesson:              'Por lección',
    alphabetical:          'Α–Ω Alfabético',
    colGreek:              'Griego',
    colEnglish:            'Español',
    colType:               'Tipo',
    colLesson:             'Lección',
    noWordsMatch:          'Ninguna palabra coincide con los filtros.',
    catNoun:               'Sustantivo',
    catVerb:               'Verbo',
    catAdjective:          'Adjetivo',
    catAdverb:             'Adverbio',
    catPreposition:        'Preposición',
    catConjunction:        'Conjunción',
    catPronoun:            'Pronombre',
    catParticle:           'Partícula',
    catOther:              'Otro',
  },
  pl: {
    appSubtitle:           'Czytnik greki koine',
    chapterLocked:         'Rozdział zablokowany',
    chapterLockedMsg:      'Ten rozdział nie jest jeszcze dostępny. Ukończ Jednostkę 1, aby odblokować kolejne rozdziały.',
    loading:               'Ładowanie rozdziału…',
    tabStory:              'Historia',
    tabVocabulary:         'Słownictwo',
    tabGrammar:            'Gramatyka',
    tabExercises:          'Ćwiczenia',
    tabVisual:             'Historia obrazkowa',
    tabConversations:      'Pytania',
    vocabFlashcards:       'Fiszki słownikowe',
    reviews:               'powtórzeń',
    tapToReveal:           'Dotknij, aby odkryć',
    tapToFlipBack:         'Dotknij, aby odwrócić',
    prev:                  '← Poprzedni',
    next:                  'Następny →',
    reveal:                'Odkryj',
    hide:                  'Ukryj',
    allWords:              'Wszystkie słowa',
    words:                 'słów',
    seen:                  'Widziane',
    clickInstruction:      'Kliknij słowo, aby zobaczyć jego znaczenie. Kliknij dwukrotnie, aby zobaczyć obrazek.',
    showTranslation:       'Pokaż tłumaczenie',
    hideTranslation:       'Ukryj tłumaczenie',
    submit:                'Prześlij',
    tryAgain:              'Spróbuj ponownie',
    answered:              'odpowiedziano',
    secMultipleChoice:     'Wielokrotny wybór',
    secTrueOrFalse:        'Prawda czy Fałsz',
    secYesOrNo:            'Tak czy Nie',
    secCorrectOrNot:       'Poprawne czy Nie',
    secFillBlank:          'Uzupełnij lukę',
    secChangePerson:       'Zmień osobę',
    secInfinitives:        'Bezokoliczniki',
    secImperatives:        'Tryb rozkazujący',
    secContractVerbs:      'Czasowniki ściągane',
    secFillCase:           'Uzupełnij przypadek',
    secPrepositions:       'Przyimki',
    secConversations:      'Pytania',
    storyOverview:         'Przegląd historii',
    illustrationSoon:      'Ilustracja wkrótce',
    tableOfContents:       'Spis treści',
    allVocabulary:         'Całe słownictwo',
    vocabSubtitle:         'Całe słownictwo · Jednostki 1 i 2',
    searchPlaceholder:     'Szukaj w języku greckim lub polskim…',
    clearFilters:          'Wyczyść filtry',
    byLesson:              'Według lekcji',
    alphabetical:          'Α–Ω Alfabetycznie',
    colGreek:              'Grecki',
    colEnglish:            'Polski',
    colType:               'Typ',
    colLesson:             'Lekcja',
    noWordsMatch:          'Żadne słowa nie pasują do filtrów.',
    catNoun:               'Rzeczownik',
    catVerb:               'Czasownik',
    catAdjective:          'Przymiotnik',
    catAdverb:             'Przysłówek',
    catPreposition:        'Przyimek',
    catConjunction:        'Spójnik',
    catPronoun:            'Zaimek',
    catParticle:           'Partykuła',
    catOther:              'Inne',
  },
  fil: {
    appSubtitle:           'Tagabasa ng Griyegong Koine',
    chapterLocked:         'Naka-lock ang Kabanata',
    chapterLockedMsg:      'Hindi pa available ang kabanatang ito. Tapusin ang Unit 1 para ma-unlock ang mga susunod na unit.',
    loading:               'Naglo-load ng kabanata…',
    tabStory:              'Kuwento',
    tabVocabulary:         'Bokabularyo',
    tabGrammar:            'Gramatika',
    tabExercises:          'Mga Pagsasanay',
    tabVisual:             'Visual na Kuwento',
    tabConversations:      'Mga Tanong',
    vocabFlashcards:       'Mga Flashcard ng Bokabularyo',
    reviews:               'mga pagbabalik-aral',
    tapToReveal:           'I-tap para ipakita',
    tapToFlipBack:         'I-tap para i-flip pabalik',
    prev:                  '← Nakaraan',
    next:                  'Susunod →',
    reveal:                'Ipakita',
    hide:                  'Itago',
    allWords:              'Lahat ng Salita',
    words:                 'mga salita',
    seen:                  'Nakita',
    clickInstruction:      'I-click ang salita para makita ang kahulugan. I-double-click para makita ang larawan.',
    showTranslation:       'Ipakita ang Salin',
    hideTranslation:       'Itago ang Salin',
    submit:                'Isumite',
    tryAgain:              'Subukan Muli',
    answered:              'nasagot',
    secMultipleChoice:     'Maramihang Pagpipilian',
    secTrueOrFalse:        'Tama o Mali',
    secYesOrNo:            'Oo o Hindi',
    secCorrectOrNot:       'Tama o Hindi',
    secFillBlank:          'Punan ang Patlang',
    secChangePerson:       'Palitan ang Tao',
    secInfinitives:        'Mga Infinitive',
    secImperatives:        'Mga Utos',
    secContractVerbs:      'Mga Contract na Pandiwa',
    secFillCase:           'Punan ang Kaso',
    secPrepositions:       'Mga Pang-ukol',
    secConversations:      'Mga Tanong',
    storyOverview:         'Buod ng Kuwento',
    illustrationSoon:      'Larawan — malapit na',
    tableOfContents:       'Talaan ng Nilalaman',
    allVocabulary:         'Lahat ng Bokabularyo',
    vocabSubtitle:         'Lahat ng bokabularyo · Mga Unit 1 at 2',
    searchPlaceholder:     'Maghanap sa Griyego o Filipino…',
    clearFilters:          'Alisin ang mga filter',
    byLesson:              'Ayon sa Aralin',
    alphabetical:          'Α–Ω Alpabetiko',
    colGreek:              'Griyego',
    colEnglish:            'Filipino',
    colType:               'Uri',
    colLesson:             'Aralin',
    noWordsMatch:          'Walang salitang tugma sa mga filter.',
    catNoun:               'Pangngalan',
    catVerb:               'Pandiwa',
    catAdjective:          'Pang-uri',
    catAdverb:             'Pang-abay',
    catPreposition:        'Pang-ukol',
    catConjunction:        'Pangatnig',
    catPronoun:            'Panghalip',
    catParticle:           'Partikula',
    catOther:              'Iba pa',
  },
}

const LanguageContext = createContext({ lang: 'en', setLang: () => {} })

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en')
  return (
    <LanguageContext.Provider value={{ lang, setLang }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}

/** Returns a ui(key) function that looks up the current language's UI string. */
export function useUI() {
  const { lang } = useLanguage()
  return (key) => UI[lang]?.[key] ?? UI.en[key] ?? key
}

/** Returns the best translation for a data field given current lang. Falls back to English. */
export function t(englishValue, translations, lang) {
  if (lang === 'en' || !translations) return englishValue
  return translations[lang] || englishValue
}
